name: "Lint and Tests Pipeline"
on: 
  push: 
    branches: 
      - main
      - develop
  pull_request: 

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Get dependencies
      run: go mod download
    - name: Build
      run: go build -v ./...
    - name: Run tests
      run: go test -v ./...
    - name: Lint
      run: golint ./... && go vet ./...
